# Generated by Django 4.0.6 on 2022-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
