# Generated by Django 4.0.6 on 2022-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_basket_price_alter_billing_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='full_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
