# Generated by Django 4.0.6 on 2022-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billing_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
