# Generated by Django 4.0.6 on 2022-07-27 11:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_color_equipment_memory_version_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='version',
        ),
        migrations.AddField(
            model_name='product',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
